name: Upload Python Package

run-name: Publish on pypi 🦅.

on:
  workflow_run:
    workflows: ['Python package']
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      if: ${{ github.ref == 'refs/heads/pypi' }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      if: ${{ github.ref == 'refs/heads/pypi' }}
      run: |
            cd main/BondOrderProcessing
            dir
            python3 -m pip install --upgrade pip
            python3 -m pip install --upgrade setuptools
            python3 -m pip install --upgrade build
            python3 -m pip install twine
            python3 -m pip install -e .
            python3 -m build
            cd dist
            tar -xvf bond_order_processing-1.0.8.tar.gz
            dir
            cd ..
    - name: Publish package to TestPyPI
      if: ${{ github.ref == 'refs/heads/pypi' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: main/BondOrderProcessing/dist/