name: Upload Python Package

run-name: Publish on pypi 🦅.

on:  
  push:
    branches: [ "pypi" ]

permissions:
  contents: read
  repository-projects: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.2.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Commit & Push changes to Readme'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 2
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
            cd main/BondOrderProcessing
            dir
            python3 -m pip install --upgrade pip
            python3 -m pip install --upgrade setuptools
            python3 -m pip install --upgrade build
            python3 -m pip install twine
            python3 -m pip install -e .
            python3 -m build
            cd dist
            tar -xvf bond_order_processing-1.0.8.tar.gz
            dir
            cd ..
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: main/BondOrderProcessing/dist/