name: Python package

run-name: 🤖 Unit test of app run by ${{ github.actor }}🤖

on: [push]

permissions:
  contents: read
  repository-projects: read
  contents: read
  pages: write
  id-token: write

jobs:
  Test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        python-version: "3.10"
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        dir
        python -m pytest --doctest-modules main/BondOrderProcessing/bond_order_processing/input_data.py
        python -m pytest --doctest-modules main/BondOrderProcessing/bond_order_processing/__init__.py
        python -m pytest --doctest-modules main/Settings/settings.py
        python -m pytest --doctest-modules main/BondOrderProcessing/bond_order_processing/calculations_for_atoms_lists.py
        python -m pytest -s --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=main/BondOrderProcessing/bond_order_processing test test/ | tee pytest-coverage.txt
    
    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml

    - name: Update Readme with Coverage Html
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' main/BondOrderProcessing/README.md
    - name: Commit & Push changes to Readme 1
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: actions-js/push@master
      with:
        branch: 'master'
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit & Push changes to Readme 2
      if: ${{ github.ref == 'refs/heads/pypi' }}
      uses: actions-js/push@master
      with:
        branch: 'pypi'
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}

  #ruchamianie zewnętrznego workflow
  publish-on-pypi:
    if: ${{ github.ref == 'refs/heads/pypi' }}
    uses: ./.github/workflows/publish.yml
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  #ruchamianie zewnętrznego workflow
  generate-doc:
    if: ${{ github.ref == 'refs/heads/pypi' }}
    uses: ./.github/workflows/docs.yml




