name: Python package
#below variable is for date.
run-name: 🤖 Unit test of app run by ${{ github.actor }}🤖

on: [push]


permissions:
  contents: read

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        python-version: "3.10"
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --doctest-modules main/BondOrderCalculations/BondOrderCalculations/input_data.py
        pytest --doctest-modules main/BondOrderCalculations/BondOrderCalculations/__init__.py
        pytest --doctest-modules main/Settings/settings.py
        pytest -s --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=main/BondOrderCalculations/BondOrderCalculations test/ | tee pytest-coverage.txt
    
    - name: Pytest coverage comment
      if: ${{ github.ref == 'refs/heads/master' }}
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml

    - name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' main/BondOrderCalculations/readme.md
    - name: Commit & Push changes to Readme
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "The job is done!!!"

