name: Python package
#below variable is for date.
run-name: 🤖 Unit test of app run by ${{ github.actor }}🤖

on: [push]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --doctest-modules main/BondOrderCalculations/BondOrderCalculations/input_data.py
        pytest --doctest-modules main/BondOrderCalculations/BondOrderCalculations/__init__.py
        pytest --doctest-modules main/Settings/settings.py
        pytest -s --junitxml=pytest.xml --cov-report "xml:coverage.xml" --cov=main/BondOrderCalculations/BondOrderCalculations test/ > pytest-coverage.txt
    
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: ./coverage.xml
        junitxml-path: ./pytest.xml
  
    - run: echo "The job is done!!!"